### ISSUE TITLE
Hardware scaler isn't full screen.

### ISSUE THREAD

**Issue by 133794m3r** [Nebuleon/ReGBA#12]
I just got back into it and noticed it's only aspect scalingwhich completely negates any reason to use the hardware scaler. I thought the ipu was able to scale to any arbitrary resolutions apparently i was wrong and the ipu is literal shit or the code didn't do full screen scaling.

**Comment by Nebuleon** [comment]
What a thing to see as an email, first thing after waking up.

If you'd rather have an immediate choice in the matter, you can use the software aspect and full-screen scalers.

But if you'd set your outrage aside for just a moment, and consult this page:

http://wiki.gcw-zero.com/Quick_Start_Guide#Button_Combinations

you would see that Power+A is able to change the aspect ratio of an application using the hardware scaler on the fly.

But I agree with you, it's much more fun to just call the entire hardware literal shit.
